# 1. Etapa de construcción
FROM maven:3.8-openjdk-17 AS build
WORKDIR /app
# Como el Root Directory es 'backend', esto ya copia los archivos desde allí
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# 2. Etapa final (ejecución)
FROM eclipse-temurin:17-jdk-jammy
WORKDIR /app
# Ajustamos la copia del .jar para que sea específica al nombre de tu archivo
COPY --from=build /app/target/politicas-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]