# 1. Etapa de construcción
FROM maven:3.8-openjdk-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# 2. Etapa final (ejecución)
FROM eclipse-temurin:17-jdk-jammy
WORKDIR /app
# Copia el jar generado en la etapa anterior
COPY --from=build /app/target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]