# 1. Etapa de construcción
FROM maven:3.8-openjdk-17 AS build
WORKDIR /app

# AQUÍ ES LA CLAVE: copiamos desde la carpeta backend hacia adentro
COPY backend/pom.xml .
COPY backend/src ./src

# Compilamos
RUN mvn clean package -DskipTests

# 2. Etapa final (ejecución)
FROM eclipse-temurin:17-jdk-jammy
WORKDIR /app
# Copiamos el .jar desde la carpeta target de la etapa 'build'
COPY --from=build /app/target/politicas-0.0.1-SNAPSHOT.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]